import React from 'react';
import { FileText, Shield, Zap, Scale, BrainCircuit, DatabaseZap, Landmark } from 'lucide-react';
import Header from './Header';

const Terms: React.FC = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 via-black to-gray-950 text-white overflow-hidden">
      <Header />
      <div className="absolute inset-0 z-0 pt-16">
        <div className="absolute top-0 left-0 w-full h-full bg-grid-pattern opacity-10"></div>
        <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-blue-900/20 via-transparent to-purple-900/20"></div>
      </div>
      <div className="container mx-auto px-4 py-24 relative z-10 pt-32">
        <div className="text-center mb-20">
          <h1 className="text-7xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500 mb-6 animate-fade-in-down">
            Terms of Service
          </h1>
          <p className="text-xl text-gray-400 max-w-3xl mx-auto leading-relaxed animate-fade-in-up">
            Our commitment to transparency and fairness is reflected in our Terms of Service. Please read them carefully.
          </p>
        </div>
        <div className="max-w-4xl mx-auto bg-gray-900/50 backdrop-blur-lg p-10 rounded-2xl border border-gray-700/50 animate-fade-in-zoom">
          <div className="prose prose-invert max-w-none">
            <p className="text-gray-400 text-sm mb-8">Last updated: July 31, 2025</p>
            
            <h2><FileText className="inline-block w-6 h-6 mr-2" />1. Universal Agreement & Binding Contract</h2>
            <p>By accessing, interfacing with, or utilizing any of our services, you hereby enter into a legally binding agreement with TraderEdge Pro ("the Company"). This agreement extends to all current and future features, tools, and services. If you do not agree to these terms, you are prohibited from using our services.</p>
            
            <h2><Zap className="inline-block w-6 h-6 mr-2" />2. Service Description & Advanced Disclaimers</h2>
            <p>TraderEdge Pro offers a sophisticated suite of analytical tools, AI-driven insights, and educational content for informational purposes only. We are not a financial institution, broker, or investment advisor. All information, signals, and analyses are generated by complex algorithms and should not be construed as financial advice. Trading in any market carries substantial risk, and you should not risk more than you are prepared to lose. Past performance is not indicative of future results, and any reliance on our data is at your own risk.</p>

            <h2><BrainCircuit className="inline-block w-6 h-6 mr-2" />3. AI & Algorithmic Liability</h2>
            <p>Our services incorporate advanced artificial intelligence and machine learning algorithms. While we strive for accuracy, you acknowledge that these systems are probabilistic and may have inherent errors or biases. You agree to hold TraderEdge Pro harmless for any decisions, trades, or actions you take based on the output of our AI systems. We are not liable for any financial losses or damages resulting from the use of our algorithmic tools.</p>

            <h2><DatabaseZap className="inline-block w-6 h-6 mr-2" />4. Data Privacy in the Quantum Age</h2>
            <p>We employ state-of-the-art encryption and data protection protocols. By using our services, you consent to the collection and use of your data as described in our Privacy Policy. This includes anonymized data for training our AI models. We will not sell your personal data to third parties. You acknowledge that in the age of quantum computing, no data is ever 100% secure, and you agree to hold us harmless for any data breaches that may occur despite our security measures.</p>

            <h2><Shield className="inline-block w-6 h-6 mr-2" />5. Absolute No Legal Action & Mandatory Arbitration</h2>
            <p>To the fullest extent permitted by law, you irrevocably waive your right to bring any form of legal action, including lawsuits, class actions, or any other legal proceedings against TraderEdge Pro, its directors, employees, or affiliates. Any dispute, claim, or controversy arising from these Terms shall be resolved through binding arbitration administered by a neutral, mutually agreed-upon arbitration service. You agree to be responsible for your own legal fees in any such proceeding.</p>

            <h2><Landmark className="inline-block w-6 h-6 mr-2" />6. Cyber-Jurisdiction Clause</h2>
            <p>This agreement is governed by the laws of the digital realm and the jurisdiction where our servers are physically located. You agree that any legal disputes will be handled within this jurisdiction, regardless of your own location. This choice of jurisdiction is final and non-negotiable.</p>

            <h2><Scale className="inline-block w-6 h-6 mr-2" />7. Governing Law & Severability</h2>
            <p>These Terms are governed by and construed in accordance with the laws of the jurisdiction in which the company is registered. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the Terms will otherwise remain in full force and effect and enforceable.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Terms;
